import React from 'react';
import { PERSONAS } from '../constants';

interface LandingPageProps {
    onEnter: () => void;
    onContactEnterprise: () => void;
    onChoosePlan: (plan: 'greenhorn' | 'vigilante' | 'sentinel') => void;
}

const FeatureCard: React.FC<{ icon: React.ReactElement; title: string; children: React.ReactNode }> = ({ icon, title, children }) => (
    <div className="bg-gray-800/50 p-6 rounded-lg border border-gray-700 transform hover:scale-105 hover:border-cyan-500 transition-all duration-300 h-full">
        <div className="flex items-center mb-4">
            <div className="bg-cyan-900/50 p-2 rounded-lg mr-4">{icon}</div>
            <h3 className="text-xl font-bold text-gray-100">{title}</h3>
        </div>
        <p className="text-gray-400">{children}</p>
    </div>
);

const StepCard: React.FC<{ number: string; title: string; children: React.ReactNode }> = ({ number, title, children }) => (
     <div className="relative pl-12">
        <div className="absolute left-0 top-0 flex items-center justify-center h-10 w-10 rounded-full bg-gray-700 border-2 border-cyan-500 text-cyan-300 font-bold text-xl">
            {number}
        </div>
        <h3 className="text-xl font-bold text-gray-100 mb-2">{title}</h3>
        <p className="text-gray-400">{children}</p>
    </div>
);

const CheckIcon: React.FC = () => (
    <svg className="w-5 h-5 text-green-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
    </svg>
);

const FloatingPersonaCard: React.FC<{ persona: typeof PERSONAS[0], delay: string, position: string }> = ({ persona, delay, position }) => (
    <div className={`absolute ${position} animate-float ${delay} hidden lg:block`}>
        <div className={`flex items-center gap-3 p-3 rounded-lg border-2 bg-gray-800/80 backdrop-blur-sm ${persona.accentColor}`}>
            {persona.icon}
            <span className={`font-bold ${persona.color.split(' ')[2]}`}>{persona.name}</span>
        </div>
    </div>
);

const UserCircleIcon: React.FC = () => (
    <svg className="w-8 h-8 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
        <path fillRule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clipRule="evenodd"></path>
    </svg>
);

const TestimonialCard: React.FC<{ quote: string; name: string; title: string; }> = ({ quote, name, title }) => (
    <div className="bg-gray-800 p-8 rounded-lg border border-gray-700 h-full flex flex-col transform hover:-translate-y-2 transition-transform duration-300">
        <blockquote className="text-gray-300 italic mb-6 relative">
            <span className="absolute -top-3 -left-4 text-6xl text-cyan-500/20 font-serif">“</span>
            {quote}
        </blockquote>
        <div className="mt-auto flex items-center">
            <div className="w-12 h-12 rounded-full bg-gray-700 flex items-center justify-center mr-4">
               <UserCircleIcon />
            </div>
            <div>
                <p className="font-bold text-white">{name}</p>
                <p className="text-sm text-cyan-400">{title}</p>
            </div>
        </div>
    </div>
);

const faqs = [
    {
        question: "What kind of targets can I analyze?",
        answer: "You can analyze websites (by providing a URL), applications (by describing their functionality, like 'a social media app for pet owners'), or even code snippets. The more detail you provide, the more accurate the analysis will be."
    },
    {
        question: "Is the analysis based on a real-time scan?",
        answer: "Cyber Sentinel AI performs its analysis based on the information you provide and its extensive knowledge base of security vulnerabilities and attack patterns. It does not perform live network requests or penetration tests on the target URL."
    },
    {
        question: "How does this differ from traditional vulnerability scanners?",
        answer: "Traditional scanners often look for known signatures and patterns. Our tool uses an AI agent to simulate the mindset and creativity of different types of hackers, allowing it to uncover logical flaws and novel attack vectors that automated tools might miss."
    },
    {
        question: "Can I use the generated reports for compliance?",
        answer: "The reports provide valuable insights and can be a strong starting point for security audits and compliance documentation. However, they are generated by an AI agent and should be reviewed by a qualified security professional before being used for official compliance purposes."
    }
];

const testimonials = [
    {
        quote: "Cyber Sentinel AI gave us insights we never would have found with our automated tools. The Black Hat persona was terrifyingly accurate.",
        name: "Jane Doe",
        title: "CTO, SecureTech"
    },
    {
        quote: "As a solo developer, this tool is invaluable. The White Hat report helped me patch three critical vulnerabilities before launch.",
        name: "John Smith",
        title: "Indie Developer"
    },
    {
        quote: "The different perspectives are a game-changer. It's like having a team of security experts on call 24/7. Highly recommended.",
        name: "Alex Johnson",
        title: "Head of Security, FinCorp"
    }
];


export const LandingPage: React.FC<LandingPageProps> = ({ onEnter, onContactEnterprise, onChoosePlan }) => {
    return (
        <main className="flex-grow">
            {/* Hero Section */}
            <section className="relative text-center pt-32 pb-32 md:pt-48 md:pb-40 px-4 bg-gray-900 bg-grid-gray-700/[0.2] overflow-hidden">
                 <FloatingPersonaCard persona={PERSONAS[0]} delay="[animation-delay:0s]" position="top-[15%] left-[10%]" />
                 <FloatingPersonaCard persona={PERSONAS[1]} delay="[animation-delay:1.5s]" position="top-[20%] right-[12%]" />
                 <FloatingPersonaCard persona={PERSONAS[2]} delay="[animation-delay:3s]" position="bottom-[25%] left-[15%]" />
                 <FloatingPersonaCard persona={PERSONAS[3]} delay="[animation-delay:4.5s]" position="bottom-[20%] right-[18%]" />
                 <FloatingPersonaCard persona={PERSONAS[4]} delay="[animation-delay:0.5s]" position="bottom-[45%] right-[5%]" />
                 <FloatingPersonaCard persona={PERSONAS[5]} delay="[animation-delay:2.5s]" position="top-[40%] left-[20%]" />

                <div className="relative z-10 animate-fade-in">
                    <h2 className="text-4xl md:text-6xl font-extrabold text-white">
                        Uncover Vulnerabilities <br />
                        <span className="text-cyan-400">Before Hackers Do.</span>
                    </h2>
                    <p className="mt-6 max-w-2xl mx-auto text-lg md:text-xl text-gray-300">
                        Leverage AI-driven hacker personas to perform comprehensive security analysis on your digital assets. Get insights from multiple perspectives to build a truly resilient system.
                    </p>
                    <button
                        onClick={onEnter}
                        className="mt-10 px-8 py-4 bg-cyan-600 text-white font-bold text-lg rounded-md hover:bg-cyan-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-900 focus:ring-cyan-500 transition-all duration-300 transform hover:scale-105 shadow-lg shadow-cyan-500/20"
                    >
                        Launch Scanner Now
                    </button>
                </div>
            </section>

            {/* Personas Section */}
            <section id="personas" className="py-20 px-4 bg-gray-800/50">
                <div className="container mx-auto">
                    <h2 className="text-3xl font-bold text-center text-white mb-4">Meet the AI Hacker Personas</h2>
                    <p className="text-center text-gray-400 mb-12 max-w-2xl mx-auto">
                        Each persona offers a unique lens, simulating real-world attacker motivations to provide a 360-degree security view.
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
                        {PERSONAS.map(persona => (
                            <div key={persona.id} className={`p-6 rounded-lg text-center border-2 transition-all duration-300 transform hover:-translate-y-2 ${persona.accentColor} bg-gray-800`}>
                                <div className="flex justify-center mb-4">{persona.icon}</div>
                                <h3 className={`text-2xl font-bold ${persona.color.split(' ')[2]}`}>{persona.name}</h3>
                                <p className="mt-2 text-gray-400">{persona.description}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </section>

             {/* How It Works Section */}
            <section className="py-20 px-4 bg-gray-900">
                 <div className="container mx-auto">
                    <h2 className="text-3xl font-bold text-center text-white mb-12">Get Your Analysis in 3 Simple Steps</h2>
                    <div className="max-w-4xl mx-auto grid md:grid-cols-3 gap-12">
                        <StepCard number="1" title="Input Target">
                            Provide a URL, application name, or a general description of your project.
                        </StepCard>
                        <StepCard number="2" title="Choose Persona">
                            Select a hacker mindset for the analysis—from ethical to malicious.
                        </StepCard>
                        <StepCard number="3" title="Receive Report">
                           Get a detailed, easy-to-understand security report in seconds.
                        </StepCard>
                    </div>
                </div>
            </section>

             {/* Features Section */}
            <section id="features" className="py-20 px-4 bg-gray-800/50">
                <div className="container mx-auto">
                    <h2 className="text-3xl font-bold text-center text-white mb-12">Why Choose Cyber Sentinel AI?</h2>
                    <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-8 max-w-4xl mx-auto">
                        <FeatureCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" /></svg>} title="Multi-Faceted Analysis">
                            Go beyond standard scans. Our AI embodies different hacker mindsets to uncover a wider range of vulnerabilities.
                        </FeatureCard>
                        <FeatureCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>} title="Actionable Intelligence">
                            Receive clear reports detailing vulnerabilities, potential attack scenarios, and concrete mitigation strategies.
                        </FeatureCard>
                         <FeatureCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>} title="Advanced AI Engine">
                           Utilizes a powerful AI model for fast, creative, and insightful security analysis that stays ahead of the curve.
                        </FeatureCard>
                        <FeatureCard icon={<svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-cyan-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.085a2 2 0 00-1.736 1.039L6.36 8.756a2 2 0 00-1.736 1.741V12" /></svg>} title="Simple & Intuitive">
                            No complex setup required. Get from question to comprehensive report in just a few clicks.
                        </FeatureCard>
                    </div>
                </div>
            </section>

            {/* Testimonials Section */}
            <section id="testimonials" className="py-20 px-4 bg-gray-900">
                <div className="container mx-auto">
                    <h2 className="text-3xl font-bold text-center text-white mb-4">Trusted by Professionals</h2>
                    <p className="text-center text-gray-400 mb-12 max-w-2xl mx-auto">
                        See what our users are saying about the power of multi-persona security analysis.
                    </p>
                    <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-8 max-w-6xl mx-auto">
                        {testimonials.map((testimonial, index) => (
                            <TestimonialCard key={index} {...testimonial} />
                        ))}
                    </div>
                </div>
            </section>

            {/* Pricing Section */}
            <section id="pricing" className="py-20 px-4 bg-gray-800/50">
                <div className="container mx-auto">
                    <h2 className="text-3xl font-bold text-center text-white mb-4">Choose Your Plan</h2>
                    <p className="text-center text-gray-400 mb-12 max-w-2xl mx-auto">
                        Flexible plans that scale with your security needs.
                    </p>
                    <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-8 max-w-7xl mx-auto items-stretch">
                        {/* Plan 1: Greenhorn */}
                        <div className="bg-gray-800 p-8 rounded-lg border border-gray-700 flex flex-col h-full transform hover:-translate-y-2 transition-transform duration-300">
                            <h3 className="text-2xl font-bold text-green-400">Greenhorn</h3>
                            <p className="mt-2 text-gray-400 h-12">Perfect for starting out and learning the ropes.</p>
                            <p className="my-6">
                                <span className="text-4xl font-extrabold text-white">$7</span>
                                <span className="text-gray-400"> / month</span>
                            </p>
                            <ul className="space-y-3 text-gray-300 mb-8 flex-grow">
                                <li className="flex items-center gap-3"><CheckIcon /> 30 scans per month</li>
                                <li className="flex items-center gap-3"><CheckIcon /> 3 hacker personas</li>
                                <li className="flex items-center gap-3"><CheckIcon /> PDF Report Export</li>
                            </ul>
                            <button onClick={() => onChoosePlan('greenhorn')} className="mt-auto w-full bg-gray-600/50 text-white font-bold py-3 px-4 rounded-md hover:bg-gray-700/80 transition-colors">Get Started</button>
                        </div>

                        {/* Plan 2: Vigilante (highlighted) */}
                        <div className="relative bg-gray-800 p-8 rounded-lg border-2 border-cyan-500 flex flex-col h-full shadow-2xl shadow-cyan-500/10 sm:scale-105 transform hover:-translate-y-2 transition-transform duration-300 animate-neon-pulse-cyan">
                            <div className="absolute top-0 -translate-y-1/2 w-full flex justify-center">
                                <span className="bg-cyan-500 text-white text-xs font-bold px-4 py-1 rounded-full uppercase tracking-wider">Most Popular</span>
                            </div>
                            <h3 className="text-2xl font-bold text-cyan-300">Vigilante</h3>
                            <p className="mt-2 text-gray-400 h-12">For freelancers and security enthusiasts.</p>
                            <p className="my-6">
                                <span className="text-4xl font-extrabold text-white">$37</span>
                                <span className="text-gray-400"> / month</span>
                            </p>
                             <ul className="space-y-3 text-gray-300 mb-8 flex-grow">
                                <li className="flex items-center gap-3"><CheckIcon /> 150 scans per month</li>
                                <li className="flex items-center gap-3"><CheckIcon /> All 6 hacker personas</li>
                                <li className="flex items-center gap-3"><CheckIcon /> PDF Report Export</li>
                                <li className="flex items-center gap-3"><CheckIcon /> Priority email support</li>
                            </ul>
                            <button onClick={() => onChoosePlan('vigilante')} className="mt-auto w-full bg-cyan-600 text-white font-bold py-3 px-4 rounded-md hover:bg-cyan-700 transition-colors">Choose Plan</button>
                        </div>
                        
                        {/* Plan 3: Sentinel */}
                        <div className="bg-gray-800 p-8 rounded-lg border border-gray-700 flex flex-col h-full transform hover:-translate-y-2 transition-transform duration-300">
                           <h3 className="text-2xl font-bold text-red-400">Sentinel</h3>
                            <p className="mt-2 text-gray-400 h-12">For professionals who need the full arsenal.</p>
                            <p className="my-6">
                                <span className="text-4xl font-extrabold text-white">$57</span>
                                <span className="text-gray-400"> / month</span>
                            </p>
                             <ul className="space-y-3 text-gray-300 mb-8 flex-grow">
                                <li className="flex items-center gap-3"><CheckIcon /> 500 scans per month</li>
                                <li className="flex items-center gap-3"><CheckIcon /> All 6 hacker personas</li>
                                <li className="flex items-center gap-3"><CheckIcon /> <span className="font-bold">PDF Report Export</span></li>
                                <li className="flex items-center gap-3"><CheckIcon /> Priority support</li>
                            </ul>
                            <button onClick={() => onChoosePlan('sentinel')} className="mt-auto w-full bg-red-600/80 text-white font-bold py-3 px-4 rounded-md hover:bg-red-700 transition-colors">Choose Plan</button>
                        </div>
                    </div>
                    
                    {/* Refund note */}
                    <p className="text-center text-xs text-gray-500 mt-8 max-w-2xl mx-auto">
                        All sales are final — no refunds. Each scan uses high-performance AI compute that cannot be recovered. We encourage everyone to try the free trial first or start from the lowest plan.
                    </p>

                    {/* Enterprise Plan Banner */}
                    <div className="mt-16 max-w-7xl mx-auto">
                        <div className="bg-gray-900/50 py-12 px-8 rounded-lg border-2 border-purple-500/50 flex flex-col md:flex-row justify-between items-center gap-8 animate-neon-pulse">
                            <div className="text-center md:text-left">
                                <h3 className="text-3xl font-bold text-purple-400">Enterprise Plan</h3>
                                <p className="mt-2 text-gray-400 max-w-lg">Custom solutions for teams with advanced security requirements, including API access and dedicated support.</p>
                            </div>
                            <div className="flex-shrink-0">
                                <button onClick={onContactEnterprise} className="w-full md:w-auto bg-purple-600/80 text-white font-bold py-3 px-6 rounded-md hover:bg-purple-700 transition-colors">
                                    Contact Us
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* FAQ Section */}
            <section id="faq" className="py-20 px-4 bg-gray-900">
                <div className="container mx-auto max-w-4xl">
                    <h2 className="text-3xl font-bold text-center text-white mb-12">Frequently Asked Questions</h2>
                    <div className="space-y-4">
                        {faqs.map((faq, index) => (
                             <details key={index} className="bg-gray-800 p-5 rounded-lg group border border-gray-700 hover:border-gray-600 transition-colors">
                                <summary className="font-semibold text-lg text-gray-100 cursor-pointer list-none flex items-center justify-between">
                                    {faq.question}
                                    <svg className="w-5 h-5 transition-transform duration-300 group-open:rotate-90 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path></svg>
                                </summary>
                                <p className="mt-4 text-gray-300">{faq.answer}</p>
                            </details>
                        ))}
                    </div>
                </div>
            </section>

        </main>
    );
};